### ISSUE TITLE
Mecanismo de Autenticação

### ISSUE THREAD

**Issue by Patrick-Santana** [josejhonata/Coliseu#10]
- Eu como desenvolvedor , desejo implementar, um mecanismo de autenticação , que possibilite o usuário , realizar o
login , no sistema. 

- [x] Mecanismo de Autenticação , utilizando o breeze

**Comment by lilialnas** [comment]
História técnica tem padrão de escrita, viu? @Patrick-Santana

**Comment by Patrick-Santana** [comment]
skksksk  S2 ksksks, por leves momentos , pensei que iria passar despercebido kskskks
