### ISSUE TITLE
Criação do modelo de banco de dados

### ISSUE THREAD

**Issue by lilialnas** [josejhonata/Coliseu#3]
Eu como desenvolvedor quero criar o modelo de dados para definir as entidades do sistema.

**Comment by Patrick-Santana** [comment]
![ideal1](https://user-images.githubusercontent.com/48485663/104755785-a94bc680-5739-11eb-8910-52118782ae81.png)


minha ideia de BD

**Comment by Patrick-Santana** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/48485663/104982099-b0e4c700-59e8-11eb-96de-0a285d4ecddf.png)

**Comment by Patrick-Santana** [comment]
Update , No nosso modelo de dados, Baseado Nas correções de Professor Rani e Lili S2

**Comment by Patrick-Santana** [comment]
EquipamAMento KKKKKKKKKKKK
